shop.Web/Controllers/OrdersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using shop.Web.Data;
using shop.Web.Data.Entities;
using shop.Web.Data.Repositories;
using shop.Web.Helpers;
using shop.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace shop.Web.Controllers
{
    [Authorize]
    public class OrdersController:Controller
    {
        private readonly IOrderRepository orderRepository;
        private readonly IProductRepository productRepository;
        private readonly DataContext context;

        public OrdersController(IOrderRepository orderRepository,IProductRepository productRepository,DataContext context)
        {
            this.orderRepository = orderRepository;
            this.productRepository = productRepository;
            this.context = context;
        }

        //aqui es donde le voy a decir que me pinte la tabla de ordener
        public async Task<IActionResult> Index()
        {
           
                var model = await orderRepository.GetOrdersAsync(this.User.Identity.Name);
                return View(model);
        
        }
              

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> SubmitOrders()
        {
            var model = await orderRepository.GetOrdersAsync(this.User.Identity.Name);
            return View(model);
        }

        public async Task<IActionResult> Create()
        {//aqui me almacena los temporales que el usuario me haya cargado
            var model = await this.orderRepository.GetDetailTempsAsync(this.User.Identity.Name);
            return this.View(model);
        }

        public IActionResult AddProduct()
        {//aqui me pinta el combobox
            var model = new AddItemViewModel
            {
                Quantity = 1,
                Products = this.productRepository.GetComboProducts()
            };

            return View(model);
        }


        [HttpPost]
        public async Task<IActionResult> AddProduct(AddItemViewModel model)
        {//aqui me muestra los productos y que me agregue un items
            if (this.ModelState.IsValid)
            {
                await this.orderRepository.AddItemToOrderAsync(model, this.User.Identity.Name);
                return this.RedirectToAction("Create");
            }

            return this.View(model);
        }

        public async Task<IActionResult> DeleteItem(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            await this.orderRepository.DeleteDetailTempAsync(id.Value);
            return this.RedirectToAction("Create");
        }

        public async Task<IActionResult> Increase(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            await this.orderRepository.ModifyOrderDetailTempQuantityAsync(id.Value, 1);
            return this.RedirectToAction("Create");
        }

        public async Task<IActionResult> Decrease(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            await this.orderRepository.ModifyOrderDetailTempQuantityAsync(id.Value, -1);
            return this.RedirectToAction("Create");
        }

            //con este metodo confirmo la orden 
        public async Task<IActionResult> ConfirmOrder()
        {
            var response = await this.orderRepository.ConfirmOrderAsync(this.User.Identity.Name);
            if (response)
            {
                return this.RedirectToAction("Index");
            }

            return this.RedirectToAction("Create");
        }



        // GET: Products/Delete/5
      
        public async Task<IActionResult> DeleteOrder(int? id)
        { 
            if (id == null)
            {
                return NotFound();
            }

            var order = await this.orderRepository.GetByIdAsync(id.Value);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }
        // POST: Products/Delete/5
        [HttpPost, ActionName("DeleteOrder")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteOrderConfirm(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            await this.orderRepository.DeleteOrderDetails(id.Value);
            await this.orderRepository.DeleteOrderAsync(id.Value);
            return this.RedirectToAction("Index");
        }

        public async Task<IActionResult> Details(int? id)
        {

            var prueba = context.OrderDetails.FromSql("SELECT * FROM dbo.OrderDetails WHERE OrderId = {0}", id);

            var aux = prueba.Select(o => o.Product.Id);

        
         
                int? IdDetails = aux.First();
                var product = await this.productRepository.GetByIdAsync(IdDetails.Value);
                

                if (id == null)
                {
                    return new NotFoundViewResult("ProductNotFound");
                }
                //TODO IMPLEMENTAR UNA LISTA              
                                                                      
            return View(product);
        }




    }
}

shop.Web/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using shop.Web.Data;
using shop.Web.Data.Entities;
using shop.Web.Helpers;
using shop.Web.Models;
using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace shop.Web.Controllers
{// aqui le digo que necesita autorizacion
    
    public class ProductsController : Controller
    {
        private readonly IProductRepository productRepository;

        private readonly IUserHelper userHelper;
        private readonly DataContext context;

        public ProductsController(IProductRepository productRepository, IUserHelper userHelper,DataContext context)
        {
            this.productRepository = productRepository;
            this.userHelper = userHelper;
            this.context = context;
        }

        // GET: Products
        
        public IActionResult Index()
        {
            return View(this.productRepository.GetAll().OrderBy(p=> p.Name));
        }

        // GET: Products/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new NotFoundViewResult("ProductNotFound");
            }

            var product = await this.productRepository.GetByIdAsync(id.Value);
            if (product == null)
            {
                return new NotFoundViewResult("ProductNotFound");
            }

            return View(product);
        }

        // GET: Products/Create
        [Authorize(Roles = "Admin")]

        public IActionResult Create()
        {
            return View();
        }

        // POST: Products/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ProducViewModel view)
        {
            if (ModelState.IsValid)
            {
                var path = string.Empty;

                if (view.ImageFile != null && view.ImageFile.Length > 0)
                {
                    var guid = Guid.NewGuid().ToString();
                    var file = $"{guid}.jpg";

                    path = Path.Combine(
                        Directory.GetCurrentDirectory(), 
                        "wwwroot\\images\\Products", 
                        file); //aqui le estoy concatenando el nombre a la ruta para saber donde esta la imagen

                    using (var stream = new FileStream(path, FileMode.Create))
                    {
                        await view.ImageFile.CopyToAsync(stream);
                    }
                     // aqui le estoy diciendo que tome la ruta relativa segun el ambiente 
                     //donde lo estoy ejecutando

                    path = $"~/images/Products/{file}";
                }

                // estoy conviritnedo el producto a una view para poder mandarlo con la ruta
                var product = this.ToProduct(view, path);

                // TODO: Pending to change to: this.User.Identity.Name CAMBIO HECHO!
                product.User = await this.userHelper.GetUserByEmailAsync("this.User.Identity.Name");
                await this.productRepository.CreateAsync(product);
                return RedirectToAction(nameof(Index));
            }

            return View(view);
        }

        private Product ToProduct(ProducViewModel view, string path)
        {
            return new Product
            {
                Id = view.Id,
                ImageUrl = path,
                IsAvailabe = view.IsAvailabe,
                LastPurchase = view.LastPurchase,
                LastSale = view.LastSale,
                Name = view.Name,
                Price = view.Price,
                Stock = view.Stock,
                User = view.User

            };
        }

        // GET: Products/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await this.productRepository.GetByIdAsync(id.Value);
            if (product == null)
            {
                return NotFound();
            }

            var view = this.ToProductViewModel(product);
            return View(view);
        }

        private ProducViewModel ToProductViewModel(Product product)
        {
            return new ProducViewModel
            {
                Id = product.Id,
                IsAvailabe = product.IsAvailabe,
                LastPurchase = product.LastPurchase,
                LastSale = product.LastSale,
                ImageUrl = product.ImageUrl,
                Name = product.Name,
                Price = product.Price,
                Stock = product.Stock,
                User = product.User

            };
        }

        // POST: Products/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(ProducViewModel view)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    // aqui le estoy diciendo que me guarde la imagen original
                    var path =view.ImageUrl;

                    // imagefile es la nueva foto.. si el usuario selecciono una nueva foto
                    if (view.ImageFile != null && view.ImageFile.Length > 0)
                    {
                        var guid = Guid.NewGuid().ToString();
                        var file = $"{guid}.jpg";

                        path = Path.Combine(
                            Directory.GetCurrentDirectory(),
                            "wwwroot\\images\\Products",
                            file); //aqui le estoy concatenando el nombre a la ruta para saber donde esta la imagen

                        using (var stream = new FileStream(path, FileMode.Create))
                        {
                            await view.ImageFile.CopyToAsync(stream);
                        }
                        // aqui le estoy diciendo que tome la ruta relativa segun el ambiente 
                        //donde lo estoy ejecutando

                        path = $"~/images/Products/{file}";
                    }

                    // estoy conviritnedo el producto a una view para poder mandarlo con la ruta
                    var product = this.ToProduct(view, path);


                   // TODO: Pending to change to: this.User.Identity.Name
                    product.User = await this.userHelper.GetUserByEmailAsync("this.User.Identity.Name");
                    await this.productRepository.UpdateAsync(product);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!await this.productRepository.ExistAsync(view.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            return View(view);
        }

        // GET: Products/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await this.productRepository.GetByIdAsync(id.Value);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {

            var prueba = context.OrderDetails.FromSql("SELECT * FROM dbo.OrderDetails WHERE ProductId = {0}", id);
            var IdPrueba = prueba.Select(o => o.Id);
           

            if (IdPrueba.Any() == true)
            {
                return new NotFoundViewResult("ProductExisting");
               
            }
                    
            var product = await this.productRepository.GetByIdAsync(id);
            await this.productRepository.DeleteAsync(product);
            return RedirectToAction(nameof(Index));
        }


        public IActionResult ProductNotFound()
        {
            return this.View();
        }


    }
}

shop.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - shop.Web</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link href="~/node_modules/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
        <link href="~/node_modules/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css" rel="stylesheet" />
        <link rel="stylesheet" href="~/css/site.css" />

    </environment>

    
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <link href="~/node_modules/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css" rel="stylesheet" />
        <link href="~/node_modules/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
    </environment>
</head>
<body>
    <nav class="rd-navbar-nav-wrap toggle-original-elements">
        <div class="container">
                   <div class="navbar-collapse collapse">
                       <ul class="nav navbar-nav">
                           <li class="rd-nav-item active">
                               <img src="~/images/dise.jpg" alt="ASP.NET" class="img-responsive glyphicon-align-center" />
                           </li>
                           <li class="rd-nav-item active">
                               <a asp-area="" asp-controller="Home" asp-action="Index" class="rd-nav-link">
                                   Pagina Principal
                               </a>
                           </li>
                           <li class="rd-nav-item active">
                               <a asp-area="" asp-controller="Home" asp-action="About" class="rd-nav-link">
                                   Acerca
                               </a>
                           </li>
                           <li class="rd-nav-item active">
                               <a asp-area="" asp-controller="Home" asp-action="Contact" class="rd-nav-link">
                                   Contactenos
                               </a>
                           </li>
                           <li class="rd-nav-item active">
                               <a asp-area="" asp-controller="Products" asp-action="Index" class="rd-nav-link">
                                   Productos
                               </a>
                           </li>

                           <li><a asp-area="" asp-controller="Orders" asp-action="Index">Ordenes</a></li>


                           @if (this.User.IsInRole("Admin"))
                           {
                               <th>
                               <li><a asp-area="" asp-controller="Orders" asp-action="SubmitOrders">Despacho Ordenes</a></li>
                               </th>
                           }

                       



                       </ul>
                <ul class="nav navbar-nav navbar-right">
                    @if (this.User.Identity.IsAuthenticated)
                    {
                        <li><a asp-area="" asp-controller="Account" asp-action="ChangeUser">@this.User.Identity.Name</a></li>
                        <li><a asp-area="" asp-controller="Account" asp-action="Logout">Logout</a></li>
                    }
                    else
                    {
                        <li><a asp-area="" asp-controller="Account" asp-action="Login">Login</a></li>
                    }
                </ul>
<br /><br />
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; https://postrejuanita.azurewebsites.net</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="~/node_modules/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>

    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>

        <script src="~/node_modules/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>
        <script src="~/js/site.min.js" asp-append-version="true"></script> 
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>